name: build and test:dev


on:
  workflow_call:
      secrets:
            SNYK_TOKEN:
                required: true
 
  pull_request:
    branches-ignore:    
      - 'releases/**'
  push:
    branches-ignore:    
      - 'releases/**'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build


